to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import (
    index,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    compete_undo_task,
)

app_name = "todo"

urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/compete_undo_task/",
        compete_undo_task,
        name="compete-undo-task",
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    def __str__(self):
        return self.content

todo/forms.py
from django import forms
from .models import Task


class TaskBasedForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        required=False,
        widget=forms.TextInput(attrs={'type': 'datetime-local'})
    )


class TaskCreateForm(TaskBasedForm):
    class Meta:
        model = Task
        fields = "__all__"


class TaskUpdateForm(TaskBasedForm):
    class Meta:
        model = Task
        fields = ("deadline", )

todo/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskCreateForm, TaskUpdateForm
from todo.models import Tag, Task


def index(request: HttpRequest) -> HttpResponse:
    context = {
        "num_tasks": Task.objects.count(),
        "num_tags": Tag.objects.count(),
        "completed_tasks": Task.objects.filter(status=True).count(),
    }
    return render(
        request,
        "todo/index.html",
        context=context)


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 3
    ordering = ['status', '-create']


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


def compete_undo_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.status = not task.status
    task.save()
    return HttpResponseRedirect(reverse_lazy('todo:task-list'))


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 7
    ordering = ["name"]


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ['name']
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ['name']
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Home page</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/images/favicon.png" type="image/x-icon">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Prev
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
          <span class="page-link">
            {{ page_obj.number }} of {{ paginator.num_pages }}
          </span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Next
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% block sidebar %}
  <ul class="sidebar-nav list-group">
    <li class="list-group-item">
      <a href="{% url "todo:index" %}">
        Home
      </a>
    </li>
    <li class="list-group-item">
      <a href="{% url "todo:task-list" %}">
        Tasks
      </a>
    </li>
    <li class="list-group-item">
      <a href="{% url "todo:tag-list" %}">
        Tags
      </a>
    </li>
  </ul>
{% endblock sidebar %}

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
    <h1>TO DO LIST</h1>
    <hr>
    <br>
    <h3>Main information about project:</h3>
    <br>
    <p class="description"><i>
      Home page of "To do list" django project.
    </i></p>
    <br>
    <ul>
        <li><strong>Number of tasks:</strong> {{ num_tasks }}</li>
        <li><strong>Number of tags:</strong> {{ num_tags }}</li>
        <li><strong>Tasks competed:</strong> {{ completed_tasks }}</li>
    </ul>
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Tag deletion</title>{% endblock %}
{% block content %}
  <h1>
    Delete tag
  <hr>
  </h1>
  <br>
  <p>
    Are you sure you want to delete this tag:
      <b>
        {{ tag.name }}
      </b>?
  </p>
  <br>
  <p>
    <i>
      Maybe this tag is useful?
    </i>
  </p>
  <form action="" method="post">
  {% csrf_token %}
    <br>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">
      Cancel
    </a>
    <input class="btn btn-danger" type="submit" value="No, delete tag">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% block title %}<title>Tag form</title>{% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} tag
  </h1>
  <hr>
  <br>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy }}
    <br>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">
      Back
    </a>
    <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update name, Add tag" }}">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% block title %}<title>Tags</title>{% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tags list
    <a href="{% url "todo:tag-create" %}" class="btn btn-primary link-to-page"  style="float: right">
      Add tag
    </a>
  <hr>
  </h1>
  <br>
  {% if tag_list %}
    <table class="table">
    <br>
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a class="btn btn-secondary link-to-page" href="{% url "todo:tag-update" pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a class="btn btn-secondary link-to-page" href="{% url "todo:tag-delete" pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
    <br>
  {% else %}
      <p>There are no tags...</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}
{% block title %}<title>Task deletion</title>{% endblock %}
{% block content %}
  <h1>
    Delete task
  <hr>
  </h1>
  <br>
  <p>
    Are you sure you want to delete this task:
      <b>
        {{ task.content }}
      </b>?
  </p>
  <br>
  <p>
    <i>
      Maybe you can do it?
    </i>
  </p>
  <form action="" method="post">
  {% csrf_token %}
    <br>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">
      Cancel
    </a>
    <input class="btn btn-danger" type="submit" value="No, I can't... Delete this task">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% block title %}<title>Task form</title>{% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} task
  </h1>
  <hr>
  <br>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy }}
    <br>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">
      Back
    </a>
    <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update deadline, Add task" }}">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}
{% block title %}<title>Tasks</title>{% endblock %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page"  style="float: right">
      Add task
    </a>
  <hr>
  <br>
  </h1>
  {% if task_list %}
    {% for task in task_list %}
    {% if task.status %}
      <a class="btn btn-secondary link-to-page" style="float: right" href="{% url "todo:compete-undo-task" pk=task.id %}">
        Undo
      </a>
      {% else %}
      <a class="btn btn-success link-to-page" style="float: right" href="{% url "todo:compete-undo-task" pk=task.id %}">
        Complete
      </a>
    {% endif %}
      <p>
        <strong>{{ task.content }}
          <span style="color: {% if task.status %}green{% else %}red{% endif %}">{% if task.status %}Done{% else %}Not done{% endif %}</span>
        </strong>
      </p>
      <p><strong>Created: </strong> {{ task.create }}
        {% if task.deadline %}<span style="color: red"><strong> Deadline </strong> {{ task.deadline }}</span>{% endif %}</p>
      <p>Tags:
        {% for tag in task.tags.all %}
          <i>#{{ tag.name }}</i>
        {% endfor %}
      </p>
      <p>
        <a href="{% url 'todo:task-update' pk=task.id %}" class="btn btn-primary link-to-page">
          Update task
        </a>
        <a href="{% url 'todo:task-delete' pk=task.id %}"  class="btn btn-danger link-to-page">
          Delete task
        </a>
      </p>
    <hr>
    {% endfor %}
  {% else %}
    <p>There are no tasks...</p>
  {% endif %}
{% endblock %}